AWSTemplateFormatVersion: "2010-09-09"
Description: CFn hands On 201909 {UserName}

Parameters:
  Prefix:
    Type: String
    Default: UserName
    Description: Prefix Name

  ServiceName:
    Type: String
    Default: CFn-handson

  KEYNAME:
    Type: String
    Default: KeyName
    Description: YourKeyName

  VPCID:
    Type: String
    Default: vpc-02820d3cb23c0c797
    Description: VPC ID(Do not change)

  SubnetID:
    Type: String
    Default: subnet-02326331e135155d2
    Description: Subnet ID(Do not change)

Resources:
  Ec2SecurityGroupApp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${Prefix}_${ServiceName}_app"
      GroupDescription: "web server security group"
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_${ServiceName}_app"

  Ec2InstanceServer:
    Type: "AWS::EC2::Instance"
    Properties:
      # AmazonLinux2を指定しています
      ImageId: "ami-0ff21806645c5e492"
      InstanceType: "t2.micro"
      KeyName: !Ref KEYNAME
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref Ec2SecurityGroupApp
          SubnetId: !Ref SubnetID
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_${ServiceName}_app"
